# Generated by Django 2.1.7 on 2019-02-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MGR', 'manager'), ('STD', 'employee')], max_length=25)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='leaveManagement.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Dateofleave', models.CharField(blank=True, max_length=50, null=True)),
                ('typeofleave', models.CharField(choices=[('s', 'sick'), ('c', 'casual')], default='NA', max_length=1)),
            ],
        ),
    ]
